server:
  port: 8085

mybatis:
  type-aliases-package: com.example.springdemo.bean
  mapper-locations: classpath:mapper/*.xml
  #开启MyBatis二级缓存
  configuration:
    cache-enabled: true


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/questionnaire?serverTimezone = Asia/Shanghai&characterEncoding=utf8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver


